In [1]:
import geopandas as gpd
import pandas as pd

In [2]:
osaka_geo = gpd.read_file("../data/osaka_geo/h27ka27.shp")

In [3]:
osaka_geo.shape

(8897, 36)

In [4]:
pd.set_option("max_columns", 40)
osaka_geo.head(10)

,KEY_CODE,PREF,CITY,S_AREA,PREF_NAME,CITY_NAME,S_NAME,KIGO_E,HCODE,AREA,PERIMETER,H27KAxx_,H27KAxx_ID,KEN,KEN_NAME,SITYO_NAME,GST_NAME,CSS_NAME,KIHON1,DUMMY1,KIHON2,KEYCODE1,KEYCODE2,AREA_MAX_F,KIGO_D,N_KEN,N_CITY,KIGO_I,MOJI,KBSUM,JINKO,SETAI,X_CODE,Y_CODE,KCODE1,geometry
0,27,27,362,000000,大阪府,田尻町,None,None,8101,75144.542,1311.122,5891,5890,27,大阪府,None,泉南郡,田尻町,0000,-,00,362000000,None,None,None,None,None,None,None,0,0,0,135.28641,34.39792,0000-00,"POLYGON ((135.28779 34.39860, 135.28818 34.398..."
1,27102001001,27,102,001001,大阪府,都島区,片町１丁目,None,8101,102717.012,1667.307,2171,2170,27,大阪府,None,大阪市,都島区,0010,-,01,102001001,102001001,M,None,None,None,None,片町１丁目,14,1389,965,135.52535,34.69267,0010-01,"POLYGON ((135.52410 34.69136, 135.52353 34.691..."
2,27102001002,27,102,001002,大阪府,都島区,片町２丁目,None,8101,127975.845,1780.858,6766,6765,27,大阪府,None,大阪市,都島区,0010,-,02,102001002,102001002,M,None,None,None,None,片町２丁目,15,701,487,135.53106,34.69499,0010-02,"POLYGON ((135.52979 34.69378, 135.52954 34.693..."
3,271020020,27,102,002000,大阪府,都島区,網島町,None,8101,191219.722,2060.096,8250,8249,27,大阪府,None,大阪市,都島区,0020,-,00,102002000,1020020,M,None,None,None,None,網島町,22,1291,753,135.52474,34.69442,0020-00,"POLYGON ((135.52240 34.69230, 135.52236 34.692..."
4,27102003001,27,102,003001,大阪府,都島区,東野田町１丁目,None,8101,105965.787,1327.310,523,522,27,大阪府,None,大阪市,都島区,0030,-,01,102003001,102003001,M,None,None,None,None,東野田町１丁目,29,1616,1109,135.52858,34.69602,0030-01,"POLYGON ((135.52776 34.69448, 135.52775 34.694..."
5,27102003002,27,102,003002,大阪府,都島区,東野田町２丁目,None,8101,62239.980,1049.212,8492,8491,27,大阪府,None,大阪市,都島区,0030,-,02,102003002,102003002,M,None,None,None,None,東野田町２丁目,12,440,284,135.53177,34.69741,0030-02,"POLYGON ((135.53329 34.69809, 135.53335 34.697..."
6,27102003003,27,102,003003,大阪府,都島区,東野田町３丁目,None,8101,56534.539,978.577,2442,2441,27,大阪府,None,大阪市,都島区,0030,-,03,102003003,102003003,M,None,None,None,None,東野田町３丁目,15,419,250,135.53467,34.69812,0030-03,"POLYGON ((135.53567 34.69701, 135.53447 34.696..."
7,27102003004,27,102,003004,大阪府,都島区,東野田町４丁目,None,8101,155012.504,1721.662,7891,7890,27,大阪府,None,大阪市,都島区,0030,-,04,102003004,102003004,M,None,None,None,None,東野田町４丁目,24,1391,891,135.52992,34.69946,0030-04,"POLYGON ((135.53005 34.69809, 135.52958 34.698..."
8,27102003005,27,102,003005,大阪府,都島区,東野田町５丁目,None,8101,94619.029,1520.448,1630,1629,27,大阪府,None,大阪市,都島区,0030,-,05,102003005,102003005,M,None,None,None,None,東野田町５丁目,24,1341,832,135.53551,34.70054,0030-05,"POLYGON ((135.53474 34.69905, 135.53466 34.699..."
9,27102004001,27,102,004001,大阪府,都島区,中野町１丁目,None,8101,139151.613,1586.691,740,739,27,大阪府,None,大阪市,都島区,0040,-,01,102004001,102004001,M,None,None,None,None,中野町１丁目,18,1046,671,135.52376,34.69927,0040-01,"POLYGON ((135.52504 34.69739, 135.52480 34.697..."

In [5]:
data = pd.read_csv("../data/osaka_data/tblT000865C27.txt", encoding="shift_jis", header=[0, 1])

In [6]:
data[:10]

,KEY_CODE,HYOSYO,CITYNAME,NAME,HTKSYORI,HTKSAKI,GASSAN,T000865001,T000865002,T000865003,T000865004,T000865005,T000865006,T000865007,T000865008,T000865009,T000865010,T000865011,T000865012,T000865013,T000865014,T000865015,T000865016,T000865017,T000865018,T000865019,T000865020,T000865021,T000865022,T000865023,T000865024,T000865025
,Unnamed: 0_level_1,Unnamed: 1_level_1,Unnamed: 2_level_1,Unnamed: 3_level_1,Unnamed: 4_level_1,Unnamed: 5_level_1,Unnamed: 6_level_1,総数,Ａ 農業、林業,うち農業,Ｂ 漁業,Ｃ 鉱業、採石業、砂利採取業,Ｄ 建設業,Ｅ 製造業,Ｆ 電気・ガス・熱供給・水道業,Ｇ 情報通信業,Ｈ 運輸業、郵便業,Ｉ 卸売業、小売業,Ｊ 金融業、保険業,Ｋ 不動産業、物品賃貸業,Ｌ 学術研究、専門・技術サービス業,Ｍ 宿泊業、飲食サービス業,Ｎ 生活関連サービス業、娯楽業,Ｏ 教育、学習支援業,Ｐ 医療、福祉,Ｑ 複合サービス事業,Ｒ サービス業（他に分類されないもの）,Ｓ 公務（他に分類されるものを除く）,Ｔ 分類不能の産業,雇用者（役員を含む）,自営業主（家庭内職者を含む）,家族従業者
0,27102,1,大阪市都島区,NaN,0,NaN,NaN,44395,28,25,1,3,2401,5505,186,2012,1844,6730,1130,1476,2007,3085,1418,1860,4945,240,2983,1111,5430,35413,3611,907
1,271020010,2,大阪市都島区,片町,0,NaN,NaN,1029,2,2,-,-,44,120,4,75,21,130,24,36,65,64,21,48,97,2,54,24,198,759,69,22
2,27102001001,3,大阪市都島区,片町１丁目,0,NaN,NaN,684,1,1,-,-,28,61,3,53,14,80,19,17,41,50,13,36,69,1,36,19,143,503,41,15
3,27102001002,3,大阪市都島区,片町２丁目,0,NaN,NaN,345,1,1,-,-,16,59,1,22,7,50,5,19,24,14,8,12,28,1,18,5,55,256,28,7
4,271020020,2,大阪市都島区,網島町,0,NaN,NaN,566,-,-,-,-,14,61,4,37,16,56,9,17,35,69,20,27,43,-,45,11,102,412,49,13
5,271020030,2,大阪市都島区,東野田町,0,NaN,NaN,2255,1,1,-,-,85,314,5,178,61,292,59,81,72,171,69,81,196,3,147,32,408,1657,178,50
6,27102003001,3,大阪市都島区,東野田町１丁目,0,NaN,NaN,840,1,1,-,-,35,140,2,64,22,100,26,22,24,53,20,28,64,2,39,14,184,624,48,9
7,27102003002,3,大阪市都島区,東野田町２丁目,0,NaN,NaN,179,-,-,-,-,4,26,-,29,2,21,7,7,6,10,5,3,16,-,12,3,28,140,7,5
8,27102003003,3,大阪市都島区,東野田町３丁目,0,NaN,NaN,142,-,-,-,-,3,9,-,3,3,20,4,10,4,21,7,4,16,-,18,1,19,96,24,7
9,27102003004,3,大阪市都島区,東野田町４丁目,0,NaN,NaN,550,-,-,-,-,22,62,2,31,16,73,10,29,19,47,23,19,55,1,38,8,95,392,54,14

In [7]:
data.shape

(10572, 32)

In [8]:
osaka_geo["KEY_CODE"].unique()

array(['27', '27102001001', '27102001002', ..., '273830090', '273830100',
       '273830110'], dtype=object)

In [9]:
data.columns[0]

('KEY_CODE', 'Unnamed: 0_level_1')

In [10]:
data[data[data.columns[0]]==27102]

,KEY_CODE,HYOSYO,CITYNAME,NAME,HTKSYORI,HTKSAKI,GASSAN,T000865001,T000865002,T000865003,T000865004,T000865005,T000865006,T000865007,T000865008,T000865009,T000865010,T000865011,T000865012,T000865013,T000865014,T000865015,T000865016,T000865017,T000865018,T000865019,T000865020,T000865021,T000865022,T000865023,T000865024,T000865025
,Unnamed: 0_level_1,Unnamed: 1_level_1,Unnamed: 2_level_1,Unnamed: 3_level_1,Unnamed: 4_level_1,Unnamed: 5_level_1,Unnamed: 6_level_1,総数,Ａ 農業、林業,うち農業,Ｂ 漁業,Ｃ 鉱業、採石業、砂利採取業,Ｄ 建設業,Ｅ 製造業,Ｆ 電気・ガス・熱供給・水道業,Ｇ 情報通信業,Ｈ 運輸業、郵便業,Ｉ 卸売業、小売業,Ｊ 金融業、保険業,Ｋ 不動産業、物品賃貸業,Ｌ 学術研究、専門・技術サービス業,Ｍ 宿泊業、飲食サービス業,Ｎ 生活関連サービス業、娯楽業,Ｏ 教育、学習支援業,Ｐ 医療、福祉,Ｑ 複合サービス事業,Ｒ サービス業（他に分類されないもの）,Ｓ 公務（他に分類されるものを除く）,Ｔ 分類不能の産業,雇用者（役員を含む）,自営業主（家庭内職者を含む）,家族従業者
0,27102,1,大阪市都島区,NaN,0,NaN,NaN,44395,28,25,1,3,2401,5505,186,2012,1844,6730,1130,1476,2007,3085,1418,1860,4945,240,2983,1111,5430,35413,3611,907

In [11]:
osaka_geo[osaka_geo[osaka_geo.columns[3]] == "片町"]

Empty GeoDataFrame
Columns: [KEY_CODE, PREF, CITY, S_AREA, PREF_NAME, CITY_NAME, S_NAME, KIGO_E, HCODE, AREA, PERIMETER, H27KAxx_, H27KAxx_ID, KEN, KEN_NAME, SITYO_NAME, GST_NAME, CSS_NAME, KIHON1, DUMMY1, KIHON2, KEYCODE1, KEYCODE2, AREA_MAX_F, KIGO_D, N_KEN, N_CITY, KIGO_I, MOJI, KBSUM, JINKO, SETAI, X_CODE, Y_CODE, KCODE1, geometry]
Index: []

In [12]:
osaka_geo[osaka_geo[osaka_geo.columns[5]] == "田尻町"]

,KEY_CODE,PREF,CITY,S_AREA,PREF_NAME,CITY_NAME,S_NAME,KIGO_E,HCODE,AREA,PERIMETER,H27KAxx_,H27KAxx_ID,KEN,KEN_NAME,SITYO_NAME,GST_NAME,CSS_NAME,KIHON1,DUMMY1,KIHON2,KEYCODE1,KEYCODE2,AREA_MAX_F,KIGO_D,N_KEN,N_CITY,KIGO_I,MOJI,KBSUM,JINKO,SETAI,X_CODE,Y_CODE,KCODE1,geometry
0,27,27,362,000000,大阪府,田尻町,None,None,8101,75144.542,1311.122,5891,5890,27,大阪府,None,泉南郡,田尻町,0000,-,00,362000000,None,None,None,None,None,None,None,0,0,0,135.28641,34.39792,0000-00,"POLYGON ((135.28779 34.39860, 135.28818 34.398..."
8774,273620010,27,362,001000,大阪府,田尻町,嘉祥寺,None,8101,922762.224,6194.290,6465,6464,27,大阪府,None,泉南郡,田尻町,0010,-,00,362001000,3620010,M,None,None,None,None,嘉祥寺,54,2961,1129,135.29370,34.39253,0010-00,"POLYGON ((135.28863 34.39507, 135.28833 34.394..."
8775,273620020,27,362,002000,大阪府,田尻町,吉見,None,8101,955775.424,5464.852,8458,8457,27,大阪府,None,泉南郡,田尻町,0020,-,00,362002000,3620020,M,None,None,None,None,吉見,64,3384,1327,135.28709,34.38966,0020-00,"POLYGON ((135.29458 34.38574, 135.29453 34.385..."
8776,273620030,27,362,003000,大阪府,田尻町,泉州空港中,None,8101,2630875.566,11459.680,4767,4766,27,大阪府,None,泉南郡,田尻町,0030,-,00,362003000,3620030,M,D,27,228,None,泉州空港中,2,1,1,135.24154,34.43477,0030-00,"POLYGON ((135.23307 34.43159, 135.23821 34.435..."
8777,273620040,27,362,004000,大阪府,田尻町,りんくうポート北,None,8101,249559.992,2934.208,5035,5034,27,大阪府,None,泉南郡,田尻町,0040,-,00,362004000,3620040,M,None,None,None,None,りんくうポート北,24,1581,825,135.28925,34.39996,0040-00,"POLYGON ((135.28930 34.39740, 135.28902 34.397..."
8778,273620050,27,362,005000,大阪府,田尻町,りんくうポート南,None,8101,190918.757,2159.041,3912,3911,27,大阪府,None,泉南郡,田尻町,0050,-,00,362005000,3620050,M,None,None,None,None,りんくうポート南,5,490,490,135.28400,34.39611,0050-00,"POLYGON ((135.28554 34.39861, 135.28551 34.398..."

In [13]:
data[data.columns[2]].unique()

array(['大阪市都島区', '大阪市福島区', '大阪市此花区', '大阪市西区', '大阪市港区', '大阪市大正区',
       '大阪市天王寺区', '大阪市浪速区', '大阪市西淀川区', '大阪市東淀川区', '大阪市東成区', '大阪市生野区',
       '大阪市旭区', '大阪市城東区', '大阪市阿倍野区', '大阪市住吉区', '大阪市東住吉区', '大阪市西成区',
       '大阪市淀川区', '大阪市鶴見区', '大阪市住之江区', '大阪市平野区', '大阪市北区', '大阪市中央区', '堺市堺区',
       '堺市中区', '堺市東区', '堺市西区', '堺市南区', '堺市北区', '堺市美原区', '岸和田市', '豊中市',
       '池田市', '吹田市', '泉大津市', '高槻市', '貝塚市', '守口市', '枚方市', '茨木市', '八尾市',
       '泉佐野市', '富田林市', '寝屋川市', '河内長野市', '松原市', '大東市', '和泉市', '箕面市', '柏原市',
       '羽曳野市', '門真市', '摂津市', '高石市', '藤井寺市', '東大阪市', '泉南市', '四條畷市', '交野市',
       '大阪狭山市', '阪南市', '三島郡島本町', '豊能郡豊能町', '豊能郡能勢町', '泉北郡忠岡町', '泉南郡熊取町',
       '泉南郡田尻町', '泉南郡岬町', '南河内郡太子町', '南河内郡河南町', '南河内郡千早赤阪村'], dtype=object)

In [14]:
data[data[data.columns[2]] == '泉南郡田尻町']

,KEY_CODE,HYOSYO,CITYNAME,NAME,HTKSYORI,HTKSAKI,GASSAN,T000865001,T000865002,T000865003,T000865004,T000865005,T000865006,T000865007,T000865008,T000865009,T000865010,T000865011,T000865012,T000865013,T000865014,T000865015,T000865016,T000865017,T000865018,T000865019,T000865020,T000865021,T000865022,T000865023,T000865024,T000865025
,Unnamed: 0_level_1,Unnamed: 1_level_1,Unnamed: 2_level_1,Unnamed: 3_level_1,Unnamed: 4_level_1,Unnamed: 5_level_1,Unnamed: 6_level_1,総数,Ａ 農業、林業,うち農業,Ｂ 漁業,Ｃ 鉱業、採石業、砂利採取業,Ｄ 建設業,Ｅ 製造業,Ｆ 電気・ガス・熱供給・水道業,Ｇ 情報通信業,Ｈ 運輸業、郵便業,Ｉ 卸売業、小売業,Ｊ 金融業、保険業,Ｋ 不動産業、物品賃貸業,Ｌ 学術研究、専門・技術サービス業,Ｍ 宿泊業、飲食サービス業,Ｎ 生活関連サービス業、娯楽業,Ｏ 教育、学習支援業,Ｐ 医療、福祉,Ｑ 複合サービス事業,Ｒ サービス業（他に分類されないもの）,Ｓ 公務（他に分類されるものを除く）,Ｔ 分類不能の産業,雇用者（役員を含む）,自営業主（家庭内職者を含む）,家族従業者
10444,27362,1,泉南郡田尻町,NaN,0,NaN,NaN,4058,62,62,9,-,172,416,10,39,375,526,48,51,54,205,114,157,414,17,207,852,330,3458,278,100
10445,273620010,2,泉南郡田尻町,嘉祥寺,0,NaN,NaN,1319,21,21,5,-,65,190,6,17,114,225,18,26,22,85,52,62,168,9,70,87,77,1134,113,48
10446,273620020,2,泉南郡田尻町,吉見,1,NaN,0030,1518,41,41,3,-,82,194,3,21,129,252,26,24,30,94,51,73,182,6,99,114,94,1254,148,50
10447,273620030,2,泉南郡田尻町,泉州空港中,2,20.0,NaN,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X
10448,273620040,2,泉南郡田尻町,りんくうポート北,0,NaN,NaN,732,-,-,1,-,25,32,1,1,132,48,4,1,2,26,11,21,64,2,38,234,89,648,17,2
10449,273620050,2,泉南郡田尻町,りんくうポート南,0,NaN,NaN,489,-,-,-,-,-,-,-,-,-,1,-,-,-,-,-,1,-,-,-,417,70,422,-,-

In [15]:
data[data[data.columns[2]] == "大阪市都島区"]

,KEY_CODE,HYOSYO,CITYNAME,NAME,HTKSYORI,HTKSAKI,GASSAN,T000865001,T000865002,T000865003,T000865004,T000865005,T000865006,T000865007,T000865008,T000865009,T000865010,T000865011,T000865012,T000865013,T000865014,T000865015,T000865016,T000865017,T000865018,T000865019,T000865020,T000865021,T000865022,T000865023,T000865024,T000865025
,Unnamed: 0_level_1,Unnamed: 1_level_1,Unnamed: 2_level_1,Unnamed: 3_level_1,Unnamed: 4_level_1,Unnamed: 5_level_1,Unnamed: 6_level_1,総数,Ａ 農業、林業,うち農業,Ｂ 漁業,Ｃ 鉱業、採石業、砂利採取業,Ｄ 建設業,Ｅ 製造業,Ｆ 電気・ガス・熱供給・水道業,Ｇ 情報通信業,Ｈ 運輸業、郵便業,Ｉ 卸売業、小売業,Ｊ 金融業、保険業,Ｋ 不動産業、物品賃貸業,Ｌ 学術研究、専門・技術サービス業,Ｍ 宿泊業、飲食サービス業,Ｎ 生活関連サービス業、娯楽業,Ｏ 教育、学習支援業,Ｐ 医療、福祉,Ｑ 複合サービス事業,Ｒ サービス業（他に分類されないもの）,Ｓ 公務（他に分類されるものを除く）,Ｔ 分類不能の産業,雇用者（役員を含む）,自営業主（家庭内職者を含む）,家族従業者
0,27102,1,大阪市都島区,NaN,0,NaN,NaN,44395,28,25,1,3,2401,5505,186,2012,1844,6730,1130,1476,2007,3085,1418,1860,4945,240,2983,1111,5430,35413,3611,907
1,271020010,2,大阪市都島区,片町,0,NaN,NaN,1029,2,2,-,-,44,120,4,75,21,130,24,36,65,64,21,48,97,2,54,24,198,759,69,22
2,27102001001,3,大阪市都島区,片町１丁目,0,NaN,NaN,684,1,1,-,-,28,61,3,53,14,80,19,17,41,50,13,36,69,1,36,19,143,503,41,15
3,27102001002,3,大阪市都島区,片町２丁目,0,NaN,NaN,345,1,1,-,-,16,59,1,22,7,50,5,19,24,14,8,12,28,1,18,5,55,256,28,7
4,271020020,2,大阪市都島区,網島町,0,NaN,NaN,566,-,-,-,-,14,61,4,37,16,56,9,17,35,69,20,27,43,-,45,11,102,412,49,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,27102015001,3,大阪市都島区,毛馬町１丁目,0,NaN,NaN,469,-,-,-,-,38,55,-,13,20,87,8,8,20,42,18,15,52,-,34,5,54,362,51,14
58,27102015002,3,大阪市都島区,毛馬町２丁目,0,NaN,NaN,1842,1,1,-,-,115,212,10,36,117,281,34,47,60,139,67,37,195,3,148,80,260,1435,161,37
59,27102015003,3,大阪市都島区,毛馬町３丁目,0,NaN,NaN,584,1,1,-,-,33,82,4,29,43,83,15,24,32,44,13,23,65,1,35,19,38,519,35,5
60,27102015004,3,大阪市都島区,毛馬町４丁目,0,NaN,NaN,621,2,2,-,-,49,87,-,16,44,105,12,14,16,33,14,18,67,3,48,11,82,493,56,12
61,27102015005,3,大阪市都島区,毛馬町５丁目,0,NaN,NaN,522,-,-,-,-,35,57,-,14,34,84,10,20,12,44,30,14,68,-,46,4,50,429,46,8

In [16]:
osaka_geo["S_NAME"] = osaka_geo["S_NAME"].fillna(0)

In [17]:
osaka_geo[osaka_geo["S_NAME"]==0]

,KEY_CODE,PREF,CITY,S_AREA,PREF_NAME,CITY_NAME,S_NAME,KIGO_E,HCODE,AREA,PERIMETER,H27KAxx_,H27KAxx_ID,KEN,KEN_NAME,SITYO_NAME,GST_NAME,CSS_NAME,KIHON1,DUMMY1,KIHON2,KEYCODE1,KEYCODE2,AREA_MAX_F,KIGO_D,N_KEN,N_CITY,KIGO_I,MOJI,KBSUM,JINKO,SETAI,X_CODE,Y_CODE,KCODE1,geometry
0,27,27,362,000000,大阪府,田尻町,0,None,8101,7.514454e+04,1311.122,5891,5890,27,大阪府,None,泉南郡,田尻町,0000,-,00,362000000,None,None,None,None,None,None,None,0,0,0,135.28641,34.39792,0000-00,"POLYGON ((135.28779 34.39860, 135.28818 34.398..."
149,271041000,27,104,100000,大阪府,此花区,0,None,8154,1.321406e+07,56324.244,8897,8896,27,大阪府,None,大阪市,此花区,1000,-,00,104100000,1041000,M,None,None,None,None,None,1,0,0,135.41118,34.65089,1000-00,"POLYGON ((135.41192 34.67666, 135.40714 34.674..."
267,271071000,27,107,100000,大阪府,港区,0,None,8154,3.323573e+06,37999.074,8891,8890,27,大阪府,None,大阪市,港区,1000,-,00,107100000,1071000,M,None,None,None,None,None,1,0,0,135.43576,34.65807,1000-00,"POLYGON ((135.45602 34.67513, 135.45592 34.675..."
316,271081000,27,108,100000,大阪府,大正区,0,None,8154,2.430999e+06,29353.412,8895,8894,27,大阪府,None,大阪市,大正区,1000,-,00,108100000,1081000,M,None,None,None,None,None,1,0,0,135.44468,34.64146,1000-00,"POLYGON ((135.46406 34.65784, 135.46395 34.657..."
513,271131000,27,113,100000,大阪府,西淀川区,0,None,8154,2.737339e+06,13091.428,8894,8893,27,大阪府,None,大阪市,西淀川区,1000,-,00,113100000,1131000,M,None,None,None,None,None,1,0,0,135.40937,34.68873,1000-00,"POLYGON ((135.41853 34.70327, 135.41735 34.702..."

In [18]:
data[data[data.columns[1]]==3].iloc[0, 0]

27102001001

In [19]:
type(data[data[data.columns[1]]==3].iloc[0, 0])

numpy.int64

In [20]:
len(str(data[data[data.columns[1]]==3].iloc[0, 0]))

11

In [21]:
data[data[data.columns[1]]==2].iloc[0, 0]

271020010

In [22]:
len(str(data[data[data.columns[1]]==2].iloc[0, 0]))

9

In [23]:
data[data[data.columns[1]]==1].iloc[0, 0]

27102

In [24]:
len(str(data[data[data.columns[1]]==1].iloc[0, 0]))

5

In [25]:
str(data[data[data.columns[1]]==1].iloc[0, 0]).ljust(11, "0")

'27102000000'

In [26]:
len(str(data[data[data.columns[1]]==1].iloc[0, 0]).ljust(11, "0"))

11

In [27]:
data.columns[0]

('KEY_CODE', 'Unnamed: 0_level_1')

In [28]:
data[("KEY_C", "KEY_C")] = str(data[data.columns[0]]).ljust(11, "0")

In [29]:
data.columns.get_level_values(0)

Index(['KEY_CODE', 'HYOSYO', 'CITYNAME', 'NAME', 'HTKSYORI', 'HTKSAKI',
       'GASSAN', 'T000865001', 'T000865002', 'T000865003', 'T000865004',
       'T000865005', 'T000865006', 'T000865007', 'T000865008', 'T000865009',
       'T000865010', 'T000865011', 'T000865012', 'T000865013', 'T000865014',
       'T000865015', 'T000865016', 'T000865017', 'T000865018', 'T000865019',
       'T000865020', 'T000865021', 'T000865022', 'T000865023', 'T000865024',
       'T000865025', 'KEY_C'],
      dtype='object')

In [30]:
data.columns.get_level_values(1)

Index(['Unnamed: 0_level_1', 'Unnamed: 1_level_1', 'Unnamed: 2_level_1',
       'Unnamed: 3_level_1', 'Unnamed: 4_level_1', 'Unnamed: 5_level_1',
       'Unnamed: 6_level_1', '総数', 'Ａ　農業、林業', '　うち農業', 'Ｂ　漁業',
       'Ｃ　鉱業、採石業、砂利採取業', 'Ｄ　建設業', 'Ｅ　製造業', 'Ｆ　電気・ガス・熱供給・水道業', 'Ｇ　情報通信業',
       'Ｈ　運輸業、郵便業', 'Ｉ　卸売業、小売業', 'Ｊ　金融業、保険業', 'Ｋ　不動産業、物品賃貸業',
       'Ｌ　学術研究、専門・技術サービス業', 'Ｍ　宿泊業、飲食サービス業', 'Ｎ　生活関連サービス業、娯楽業', 'Ｏ　教育、学習支援業',
       'Ｐ　医療、福祉', 'Ｑ　複合サービス事業', 'Ｒ　サービス業（他に分類されないもの）', 'Ｓ　公務（他に分類されるものを除く）',
       'Ｔ　分類不能の産業', '雇用者（役員を含む）', '自営業主（家庭内職者を含む）', '家族従業者', 'KEY_C'],
      dtype='object')

In [31]:
list(data.columns.get_level_values(0)[:7]) + list(data.columns.get_level_values(1)[7:])

['KEY_CODE',
 'HYOSYO',
 'CITYNAME',
 'NAME',
 'HTKSYORI',
 'HTKSAKI',
 'GASSAN',
 '総数',
 'Ａ\u3000農業、林業',
 '\u3000うち農業',
 'Ｂ\u3000漁業',
 'Ｃ\u3000鉱業、採石業、砂利採取業',
 'Ｄ\u3000建設業',
 'Ｅ\u3000製造業',
 'Ｆ\u3000電気・ガス・熱供給・水道業',
 'Ｇ\u3000情報通信業',
 'Ｈ\u3000運輸業、郵便業',
 'Ｉ\u3000卸売業、小売業',
 'Ｊ\u3000金融業、保険業',
 'Ｋ\u3000不動産業、物品賃貸業',
 'Ｌ\u3000学術研究、専門・技術サービス業',
 'Ｍ\u3000宿泊業、飲食サービス業',
 'Ｎ\u3000生活関連サービス業、娯楽業',
 'Ｏ\u3000教育、学習支援業',
 'Ｐ\u3000医療、福祉',
 'Ｑ\u3000複合サービス事業',
 'Ｒ\u3000サービス業（他に分類されないもの）',
 'Ｓ\u3000公務（他に分類されるものを除く）',
 'Ｔ\u3000分類不能の産業',
 '雇用者（役員を含む）',
 '自営業主（家庭内職者を含む）',
 '家族従業者',
 'KEY_C']

In [32]:
cols_name = list(data.columns.get_level_values(0)[:7]) + list(data.columns.get_level_values(1)[7:])
data.columns = cols_name

In [33]:
data.head()

,KEY_CODE,HYOSYO,CITYNAME,NAME,HTKSYORI,HTKSAKI,GASSAN,総数,Ａ 農業、林業,うち農業,Ｂ 漁業,Ｃ 鉱業、採石業、砂利採取業,Ｄ 建設業,Ｅ 製造業,Ｆ 電気・ガス・熱供給・水道業,Ｇ 情報通信業,Ｈ 運輸業、郵便業,Ｉ 卸売業、小売業,Ｊ 金融業、保険業,Ｋ 不動産業、物品賃貸業,Ｌ 学術研究、専門・技術サービス業,Ｍ 宿泊業、飲食サービス業,Ｎ 生活関連サービス業、娯楽業,Ｏ 教育、学習支援業,Ｐ 医療、福祉,Ｑ 複合サービス事業,Ｒ サービス業（他に分類されないもの）,Ｓ 公務（他に分類されるものを除く）,Ｔ 分類不能の産業,雇用者（役員を含む）,自営業主（家庭内職者を含む）,家族従業者,KEY_C
0,27102,1,大阪市都島区,NaN,0,NaN,NaN,44395,28,25,1,3,2401,5505,186,2012,1844,6730,1130,1476,2007,3085,1418,1860,4945,240,2983,1111,5430,35413,3611,907,0 27102\n1 271020010\n2 ...
1,271020010,2,大阪市都島区,片町,0,NaN,NaN,1029,2,2,-,-,44,120,4,75,21,130,24,36,65,64,21,48,97,2,54,24,198,759,69,22,0 27102\n1 271020010\n2 ...
2,27102001001,3,大阪市都島区,片町１丁目,0,NaN,NaN,684,1,1,-,-,28,61,3,53,14,80,19,17,41,50,13,36,69,1,36,19,143,503,41,15,0 27102\n1 271020010\n2 ...
3,27102001002,3,大阪市都島区,片町２丁目,0,NaN,NaN,345,1,1,-,-,16,59,1,22,7,50,5,19,24,14,8,12,28,1,18,5,55,256,28,7,0 27102\n1 271020010\n2 ...
4,271020020,2,大阪市都島区,網島町,0,NaN,NaN,566,-,-,-,-,14,61,4,37,16,56,9,17,35,69,20,27,43,-,45,11,102,412,49,13,0 27102\n1 271020010\n2 ...

In [34]:
data["KEY_C"] = data["KEY_CODE"].apply(lambda x: str(x).ljust(11, "0"))

In [35]:
data

,KEY_CODE,HYOSYO,CITYNAME,NAME,HTKSYORI,HTKSAKI,GASSAN,総数,Ａ 農業、林業,うち農業,Ｂ 漁業,Ｃ 鉱業、採石業、砂利採取業,Ｄ 建設業,Ｅ 製造業,Ｆ 電気・ガス・熱供給・水道業,Ｇ 情報通信業,Ｈ 運輸業、郵便業,Ｉ 卸売業、小売業,Ｊ 金融業、保険業,Ｋ 不動産業、物品賃貸業,Ｌ 学術研究、専門・技術サービス業,Ｍ 宿泊業、飲食サービス業,Ｎ 生活関連サービス業、娯楽業,Ｏ 教育、学習支援業,Ｐ 医療、福祉,Ｑ 複合サービス事業,Ｒ サービス業（他に分類されないもの）,Ｓ 公務（他に分類されるものを除く）,Ｔ 分類不能の産業,雇用者（役員を含む）,自営業主（家庭内職者を含む）,家族従業者,KEY_C
0,27102,1,大阪市都島区,NaN,0,NaN,NaN,44395,28,25,1,3,2401,5505,186,2012,1844,6730,1130,1476,2007,3085,1418,1860,4945,240,2983,1111,5430,35413,3611,907,27102000000
1,271020010,2,大阪市都島区,片町,0,NaN,NaN,1029,2,2,-,-,44,120,4,75,21,130,24,36,65,64,21,48,97,2,54,24,198,759,69,22,27102001000
2,27102001001,3,大阪市都島区,片町１丁目,0,NaN,NaN,684,1,1,-,-,28,61,3,53,14,80,19,17,41,50,13,36,69,1,36,19,143,503,41,15,27102001001
3,27102001002,3,大阪市都島区,片町２丁目,0,NaN,NaN,345,1,1,-,-,16,59,1,22,7,50,5,19,24,14,8,12,28,1,18,5,55,256,28,7,27102001002
4,271020020,2,大阪市都島区,網島町,0,NaN,NaN,566,-,-,-,-,14,61,4,37,16,56,9,17,35,69,20,27,43,-,45,11,102,412,49,13,27102002000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10567,27383007001,3,南河内郡千早赤阪村,大字小吹,0,NaN,NaN,129,13,13,-,-,10,14,-,-,4,14,1,1,7,10,5,9,13,2,17,8,1,102,18,8,27383007001
10568,27383007002,3,南河内郡千早赤阪村,大字小吹,0,NaN,NaN,723,4,4,-,-,38,104,7,16,42,125,11,14,30,25,15,45,137,3,61,26,20,608,90,18,27383007002
10569,273830090,2,南河内郡千早赤阪村,大字中津原,0,NaN,NaN,116,8,5,-,-,6,34,2,1,2,13,2,4,4,7,5,7,9,1,8,3,-,89,20,7,27383009000
10570,273830100,2,南河内郡千早赤阪村,大字東阪,0,NaN,NaN,192,23,22,-,-,19,26,-,-,19,34,7,2,1,5,7,7,19,2,11,7,3,154,25,12,27383010000
10571,273830110,2,南河内郡千早赤阪村,大字千早,0,NaN,NaN,96,1,-,-,-,3,15,-,3,7,14,-,2,3,9,7,5,15,2,2,6,2,79,13,3,27383011000

In [36]:
osaka_geo.head()

,KEY_CODE,PREF,CITY,S_AREA,PREF_NAME,CITY_NAME,S_NAME,KIGO_E,HCODE,AREA,PERIMETER,H27KAxx_,H27KAxx_ID,KEN,KEN_NAME,SITYO_NAME,GST_NAME,CSS_NAME,KIHON1,DUMMY1,KIHON2,KEYCODE1,KEYCODE2,AREA_MAX_F,KIGO_D,N_KEN,N_CITY,KIGO_I,MOJI,KBSUM,JINKO,SETAI,X_CODE,Y_CODE,KCODE1,geometry
0,27,27,362,000000,大阪府,田尻町,0,None,8101,75144.542,1311.122,5891,5890,27,大阪府,None,泉南郡,田尻町,0000,-,00,362000000,None,None,None,None,None,None,None,0,0,0,135.28641,34.39792,0000-00,"POLYGON ((135.28779 34.39860, 135.28818 34.398..."
1,27102001001,27,102,001001,大阪府,都島区,片町１丁目,None,8101,102717.012,1667.307,2171,2170,27,大阪府,None,大阪市,都島区,0010,-,01,102001001,102001001,M,None,None,None,None,片町１丁目,14,1389,965,135.52535,34.69267,0010-01,"POLYGON ((135.52410 34.69136, 135.52353 34.691..."
2,27102001002,27,102,001002,大阪府,都島区,片町２丁目,None,8101,127975.845,1780.858,6766,6765,27,大阪府,None,大阪市,都島区,0010,-,02,102001002,102001002,M,None,None,None,None,片町２丁目,15,701,487,135.53106,34.69499,0010-02,"POLYGON ((135.52979 34.69378, 135.52954 34.693..."
3,271020020,27,102,002000,大阪府,都島区,網島町,None,8101,191219.722,2060.096,8250,8249,27,大阪府,None,大阪市,都島区,0020,-,00,102002000,1020020,M,None,None,None,None,網島町,22,1291,753,135.52474,34.69442,0020-00,"POLYGON ((135.52240 34.69230, 135.52236 34.692..."
4,27102003001,27,102,003001,大阪府,都島区,東野田町１丁目,None,8101,105965.787,1327.310,523,522,27,大阪府,None,大阪市,都島区,0030,-,01,102003001,102003001,M,None,None,None,None,東野田町１丁目,29,1616,1109,135.52858,34.69602,0030-01,"POLYGON ((135.52776 34.69448, 135.52775 34.694..."

In [37]:
osaka_geo["KEY_C"] = osaka_geo["PREF"].astype(str) + osaka_geo["CITY"].astype(str) + osaka_geo["S_AREA"].astype(str)

In [42]:
osaka_geo.tail()

,KEY_CODE,PREF,CITY,S_AREA,PREF_NAME,CITY_NAME,S_NAME,KIGO_E,HCODE,AREA,PERIMETER,H27KAxx_,H27KAxx_ID,KEN,KEN_NAME,SITYO_NAME,GST_NAME,CSS_NAME,KIHON1,DUMMY1,KIHON2,KEYCODE1,KEYCODE2,AREA_MAX_F,KIGO_D,N_KEN,N_CITY,KIGO_I,MOJI,KBSUM,JINKO,SETAI,X_CODE,Y_CODE,KCODE1,geometry,KEY_C
8892,27383007001,27,383,007001,大阪府,千早赤阪村,大字小吹,None,8101,1941696.772,8350.971,2581,2580,27,大阪府,None,南河内郡,千早赤阪村,0070,-,01,383007001,383007001,M,None,None,None,None,大字小吹,3,255,81,135.61617,34.43767,0070-01,"POLYGON ((135.62055 34.44046, 135.62056 34.440...",27383007001
8893,27383007002,27,383,007002,大阪府,千早赤阪村,大字小吹,None,8101,362713.847,3416.303,6077,6076,27,大阪府,None,南河内郡,千早赤阪村,0070,-,02,383007002,383007002,M,None,None,None,None,大字小吹,58,1958,794,135.60675,34.43925,0070-02,"POLYGON ((135.60514 34.43636, 135.60520 34.436...",27383007002
8894,273830090,27,383,009000,大阪府,千早赤阪村,大字中津原,None,8101,2504907.178,8612.457,6074,6073,27,大阪府,None,南河内郡,千早赤阪村,0090,-,00,383009000,3830090,M,None,None,None,None,大字中津原,4,258,94,135.62515,34.43288,0090-00,"POLYGON ((135.63375 34.42802, 135.63372 34.427...",27383009000
8895,273830100,27,383,010000,大阪府,千早赤阪村,大字東阪,None,8101,4121487.802,20583.320,1879,1878,27,大阪府,None,南河内郡,千早赤阪村,0100,-,00,383010000,3830100,M,None,None,None,None,大字東阪,5,473,150,135.62721,34.44459,0100-00,"POLYGON ((135.64049 34.42799, 135.64036 34.428...",27383010000
8896,273830110,27,383,011000,大阪府,千早赤阪村,大字千早,None,8101,8623739.338,14893.256,5900,5899,27,大阪府,None,南河内郡,千早赤阪村,0110,-,00,383011000,3830110,M,None,None,None,None,大字千早,5,249,110,135.65730,34.41249,0110-00,"POLYGON ((135.66776 34.42680, 135.66764 34.426...",27383011000

In [39]:
test_osaka = osaka_geo.merge(data, left_on="KEY_C", right_on="KEY_C")

In [40]:
pd.set_option("max_columns", 80)
test_osaka.head()

,KEY_CODE_x,PREF,CITY,S_AREA,PREF_NAME,CITY_NAME,S_NAME,KIGO_E,HCODE,AREA,PERIMETER,H27KAxx_,H27KAxx_ID,KEN,KEN_NAME,SITYO_NAME,GST_NAME,CSS_NAME,KIHON1,DUMMY1,KIHON2,KEYCODE1,KEYCODE2,AREA_MAX_F,KIGO_D,N_KEN,N_CITY,KIGO_I,MOJI,KBSUM,JINKO,SETAI,X_CODE,Y_CODE,KCODE1,geometry,KEY_C,KEY_CODE_y,HYOSYO,CITYNAME,NAME,HTKSYORI,HTKSAKI,GASSAN,総数,Ａ 農業、林業,うち農業,Ｂ 漁業,Ｃ 鉱業、採石業、砂利採取業,Ｄ 建設業,Ｅ 製造業,Ｆ 電気・ガス・熱供給・水道業,Ｇ 情報通信業,Ｈ 運輸業、郵便業,Ｉ 卸売業、小売業,Ｊ 金融業、保険業,Ｋ 不動産業、物品賃貸業,Ｌ 学術研究、専門・技術サービス業,Ｍ 宿泊業、飲食サービス業,Ｎ 生活関連サービス業、娯楽業,Ｏ 教育、学習支援業,Ｐ 医療、福祉,Ｑ 複合サービス事業,Ｒ サービス業（他に分類されないもの）,Ｓ 公務（他に分類されるものを除く）,Ｔ 分類不能の産業,雇用者（役員を含む）,自営業主（家庭内職者を含む）,家族従業者
0,27,27,362,000000,大阪府,田尻町,0,None,8101,75144.542,1311.122,5891,5890,27,大阪府,None,泉南郡,田尻町,0000,-,00,362000000,None,None,None,None,None,None,None,0,0,0,135.28641,34.39792,0000-00,"POLYGON ((135.28779 34.39860, 135.28818 34.398...",27362000000,27362,1,泉南郡田尻町,NaN,0,NaN,NaN,4058,62,62,9,-,172,416,10,39,375,526,48,51,54,205,114,157,414,17,207,852,330,3458,278,100
1,27102001001,27,102,001001,大阪府,都島区,片町１丁目,None,8101,102717.012,1667.307,2171,2170,27,大阪府,None,大阪市,都島区,0010,-,01,102001001,102001001,M,None,None,None,None,片町１丁目,14,1389,965,135.52535,34.69267,0010-01,"POLYGON ((135.52410 34.69136, 135.52353 34.691...",27102001001,27102001001,3,大阪市都島区,片町１丁目,0,NaN,NaN,684,1,1,-,-,28,61,3,53,14,80,19,17,41,50,13,36,69,1,36,19,143,503,41,15
2,27102001002,27,102,001002,大阪府,都島区,片町２丁目,None,8101,127975.845,1780.858,6766,6765,27,大阪府,None,大阪市,都島区,0010,-,02,102001002,102001002,M,None,None,None,None,片町２丁目,15,701,487,135.53106,34.69499,0010-02,"POLYGON ((135.52979 34.69378, 135.52954 34.693...",27102001002,27102001002,3,大阪市都島区,片町２丁目,0,NaN,NaN,345,1,1,-,-,16,59,1,22,7,50,5,19,24,14,8,12,28,1,18,5,55,256,28,7
3,271020020,27,102,002000,大阪府,都島区,網島町,None,8101,191219.722,2060.096,8250,8249,27,大阪府,None,大阪市,都島区,0020,-,00,102002000,1020020,M,None,None,None,None,網島町,22,1291,753,135.52474,34.69442,0020-00,"POLYGON ((135.52240 34.69230, 135.52236 34.692...",27102002000,271020020,2,大阪市都島区,網島町,0,NaN,NaN,566,-,-,-,-,14,61,4,37,16,56,9,17,35,69,20,27,43,-,45,11,102,412,49,13
4,27102003001,27,102,003001,大阪府,都島区,東野田町１丁目,None,8101,105965.787,1327.310,523,522,27,大阪府,None,大阪市,都島区,0030,-,01,102003001,102003001,M,None,None,None,None,東野田町１丁目,29,1616,1109,135.52858,34.69602,0030-01,"POLYGON ((135.52776 34.69448, 135.52775 34.694...",27102003001,27102003001,3,大阪市都島区,東野田町１丁目,0,NaN,NaN,840,1,1,-,-,35,140,2,64,22,100,26,22,24,53,20,28,64,2,39,14,184,624,48,9

In [41]:
test_osaka.shape

(8903, 69)

In [43]:
test_osaka["KEY_C"].value_counts()

27361055000    14
27219301000    10
27222045000     8
27206031000     7
27222025000     6
               ..
27366002013     1
27111015001     1
27220035006     1
27215313000     1
27113011005     1
Name: KEY_C, Length: 8661, dtype: int64

In [44]:
osaka_geo["KEY_C"].value_counts()

27361055000    14
27222045000     8
27206031000     7
27143004000     6
27206047003     5
               ..
27141081000     1
27205007003     1
27217010004     1
27212058005     1
27113011005     1
Name: KEY_C, Length: 8693, dtype: int64

In [63]:
len(data["KEY_C"].value_counts()[data["KEY_C"].value_counts().values == 2])

31

In [64]:
data["KEY_C"].value_counts()[data["KEY_C"].value_counts().values == 2]

27222025000    2
27224023000    2
27208004000    2
27206058000    2
27208006000    2
27143012000    2
27202123200    2
27228005000    2
27219101000    2
27145029000    2
27222031000    2
27224017000    2
27232021000    2
27220001000    2
27202045100    2
27213038000    2
27219302000    2
27202097000    2
27213039000    2
27232001000    2
27146012000    2
27220009000    2
27208014000    2
27219301000    2
27222014000    2
27224020000    2
27228001000    2
27210157000    2
27222021000    2
27208060000    2
27232036000    2
Name: KEY_C, dtype: int64

In [58]:
osaka_geo[osaka_geo["KEY_C"] == "27361055000"]

,KEY_CODE,PREF,CITY,S_AREA,PREF_NAME,CITY_NAME,S_NAME,KIGO_E,HCODE,AREA,PERIMETER,H27KAxx_,H27KAxx_ID,KEN,KEN_NAME,SITYO_NAME,GST_NAME,CSS_NAME,KIHON1,DUMMY1,KIHON2,KEYCODE1,KEYCODE2,AREA_MAX_F,KIGO_D,N_KEN,N_CITY,KIGO_I,MOJI,KBSUM,JINKO,SETAI,X_CODE,Y_CODE,KCODE1,geometry,KEY_C
8729,273610550,27,361,055000,大阪府,熊取町,七山北,E1,8101,282383.335,8413.525,1644,1643,27,大阪府,None,泉南郡,熊取町,0550,-,00,361055000,3610550,M,None,None,None,None,七山北,17,107,35,135.36162,34.41622,0550-00,"POLYGON ((135.36607 34.41266, 135.36608 34.412...",27361055000
8730,273610550,27,361,055000,大阪府,熊取町,七山北,E10,8101,969.781,136.590,1632,1631,27,大阪府,None,泉南郡,熊取町,0550,-,00,361055000,3610550,None,D,27,208,None,七山北,0,0,0,135.36791,34.41145,0550-00,"POLYGON ((135.36781 34.41167, 135.36789 34.411...",27361055000
8731,273610550,27,361,055000,大阪府,熊取町,七山北,E11,8101,405.789,88.785,1633,1632,27,大阪府,None,泉南郡,熊取町,0550,-,00,361055000,3610550,None,D,27,208,None,七山北,0,0,0,135.36728,34.41143,0550-00,"POLYGON ((135.36748 34.41158, 135.36752 34.411...",27361055000
8732,273610550,27,361,055000,大阪府,熊取町,七山北,E12,8101,196.961,71.204,1638,1637,27,大阪府,None,泉南郡,熊取町,0550,-,00,361055000,3610550,None,D,27,208,None,七山北,0,0,0,135.36712,34.41178,0550-00,"POLYGON ((135.36724 34.41189, 135.36727 34.411...",27361055000
8733,273610550,27,361,055000,大阪府,熊取町,七山北,E13,8101,145.794,48.510,1634,1633,27,大阪府,None,泉南郡,熊取町,0550,-,00,361055000,3610550,None,D,27,208,None,七山北,0,0,0,135.36266,34.41705,0550-00,"POLYGON ((135.36259 34.41710, 135.36273 34.417...",27361055000
8734,273610550,27,361,055000,大阪府,熊取町,七山北,E14,8101,127.613,43.309,1631,1630,27,大阪府,None,泉南郡,熊取町,0550,-,00,361055000,3610550,None,D,27,208,None,七山北,0,0,0,135.36679,34.41158,0550-00,"POLYGON ((135.36676 34.41163, 135.36684 34.411...",27361055000
8735,273610550,27,361,055000,大阪府,熊取町,七山北,E2,8101,6003.509,710.404,1643,1642,27,大阪府,None,泉南郡,熊取町,0550,-,00,361055000,3610550,None,D,27,208,None,七山北,0,0,0,135.35937,34.41990,0550-00,"POLYGON ((135.35965 34.41991, 135.35964 34.419...",27361055000
8736,273610550,27,361,055000,大阪府,熊取町,七山北,E3,8101,4945.012,328.294,1639,1638,27,大阪府,None,泉南郡,熊取町,0550,-,00,361055000,3610550,None,D,27,208,None,七山北,0,0,0,135.35404,34.41974,0550-00,"POLYGON ((135.35405 34.41921, 135.35394 34.419...",27361055000
8737,273610550,27,361,055000,大阪府,熊取町,七山北,E4,8101,4379.771,373.732,1635,1634,27,大阪府,None,泉南郡,熊取町,0550,-,00,361055000,3610550,None,D,27,208,None,七山北,0,0,0,135.36651,34.41588,0550-00,"POLYGON ((135.36687 34.41613, 135.36687 34.416...",27361055000
8738,273610550,27,361,055000,大阪府,熊取町,七山北,E5,8101,2546.903,256.390,1636,1635,27,大阪府,None,泉南郡,熊取町,0550,-,00,361055000,3610550,None,D,27,208,None,七山北,0,0,0,135.36747,34.41249,0550-00,"POLYGON ((135.36784 34.41214, 135.36751 34.412...",27361055000
8739,273610550,27,361,055000,大阪府,熊取町,七山北,E6,8101,2208.265,234.778,1642,1641,27,大阪府,None,泉南郡,熊取町,0550,-,00,361055000,3610550,None,D,27,208,None,七山北,0,0,0,135.35503,34.42016,0550-00,"POLYGON ((135.35477 34.42024, 135.35475 34.420...",27361055000
8740,273610550,27,361,055000,大阪府,熊取町,七山北,E7,8101,1820.545,169.544,1641,1640,27,大阪府,None,泉南郡,熊取町,0550,-,00,361055000,3610550,None,D,27,208,None,七山北,0,0,0,135.35467,34.41975,0550-00,"POLYGON ((135.35459 34.41994, 135.35468 34.419...",27361055000
8741,273610550,27,361,055000,大阪府,熊取町,七山北,E8,8101,1189.087,176.436,1640,1639,27,大阪府,None,泉南郡,熊取町,0550,-,00,361055000,3610550,None,D,27,208,None,七山北,0,0,0,135.35973,34.42076,0550-00,"POLYGON ((135.35954 34.42056, 135.35978 34.421...",27361055000
8742,273610550,27,361,055000,大阪府,熊取町,七山北,E9,8101,1105.299,152.954,1637,1636,27,大阪府,None,泉南郡,熊取町,0550,-,00,361055000,3610550,None,D,27,208,None,七山北,0,0,0,135.36850,34.41169,0550-00,"POLYGON ((135.36827 34.41186, 135.36831 34.411...",27361055000

In [59]:
osaka_geo[osaka_geo["KEY_C"] == "27222045000"]

,KEY_CODE,PREF,CITY,S_AREA,PREF_NAME,CITY_NAME,S_NAME,KIGO_E,HCODE,AREA,PERIMETER,H27KAxx_,H27KAxx_ID,KEN,KEN_NAME,SITYO_NAME,GST_NAME,CSS_NAME,KIHON1,DUMMY1,KIHON2,KEYCODE1,KEYCODE2,AREA_MAX_F,KIGO_D,N_KEN,N_CITY,KIGO_I,MOJI,KBSUM,JINKO,SETAI,X_CODE,Y_CODE,KCODE1,geometry,KEY_C
7176,272220450,27,222,045000,大阪府,羽曳野市,壷井,E1,8101,23055.079,907.805,8633,8632,27,大阪府,None,羽曳野市,None,0450,-,00,222045000,2220450,None,None,None,None,None,壷井,11,591,226,135.61304,34.52692,0450-00,"POLYGON ((135.61255 34.52630, 135.61296 34.526...",27222045000
7177,272220450,27,222,045000,大阪府,羽曳野市,壷井,E2,8101,772942.024,6159.651,8634,8633,27,大阪府,None,羽曳野市,None,0450,-,00,222045000,2220450,M,None,None,None,None,壷井,0,0,0,135.62459,34.53191,0450-00,"POLYGON ((135.62582 34.52765, 135.62519 34.527...",27222045000
7178,272220450,27,222,045000,大阪府,羽曳野市,壷井,E3,8101,2218.381,209.846,8639,8638,27,大阪府,None,羽曳野市,None,0450,-,00,222045000,2220450,None,None,None,None,None,壷井,0,0,0,135.61754,34.53066,0450-00,"POLYGON ((135.61782 34.53074, 135.61771 34.530...",27222045000
7179,272220450,27,222,045000,大阪府,羽曳野市,壷井,E4,8101,4079.755,303.598,8632,8631,27,大阪府,None,羽曳野市,None,0450,-,00,222045000,2220450,None,None,None,None,None,壷井,0,0,0,135.61211,34.53434,0450-00,"POLYGON ((135.61182 34.53447, 135.61195 34.534...",27222045000
7180,272220450,27,222,045000,大阪府,羽曳野市,壷井,E5,8101,548.632,108.936,8636,8635,27,大阪府,None,羽曳野市,None,0450,-,00,222045000,2220450,None,None,None,None,None,壷井,0,0,0,135.61731,34.52971,0450-00,"POLYGON ((135.61729 34.52990, 135.61744 34.529...",27222045000
7181,272220450,27,222,045000,大阪府,羽曳野市,壷井,E6,8101,811.066,148.777,8635,8634,27,大阪府,None,羽曳野市,None,0450,-,00,222045000,2220450,None,None,None,None,None,壷井,0,0,0,135.61650,34.52826,0450-00,"POLYGON ((135.61653 34.52804, 135.61638 34.528...",27222045000
7182,272220450,27,222,045000,大阪府,羽曳野市,壷井,E7,8101,1666.883,232.416,8637,8636,27,大阪府,None,羽曳野市,None,0450,-,00,222045000,2220450,None,None,None,None,None,壷井,0,0,0,135.61684,34.52987,0450-00,"POLYGON ((135.61704 34.53033, 135.61700 34.529...",27222045000
7183,272220450,27,222,045000,大阪府,羽曳野市,壷井,E8,8101,1259.984,150.377,8638,8637,27,大阪府,None,羽曳野市,None,0450,-,00,222045000,2220450,None,None,None,None,None,壷井,0,0,0,135.61617,34.53048,0450-00,"POLYGON ((135.61628 34.53025, 135.61619 34.530...",27222045000

In [60]:
data[data["KEY_C"] == "27222045000"]

,KEY_CODE,HYOSYO,CITYNAME,NAME,HTKSYORI,HTKSAKI,GASSAN,総数,Ａ 農業、林業,うち農業,Ｂ 漁業,Ｃ 鉱業、採石業、砂利採取業,Ｄ 建設業,Ｅ 製造業,Ｆ 電気・ガス・熱供給・水道業,Ｇ 情報通信業,Ｈ 運輸業、郵便業,Ｉ 卸売業、小売業,Ｊ 金融業、保険業,Ｋ 不動産業、物品賃貸業,Ｌ 学術研究、専門・技術サービス業,Ｍ 宿泊業、飲食サービス業,Ｎ 生活関連サービス業、娯楽業,Ｏ 教育、学習支援業,Ｐ 医療、福祉,Ｑ 複合サービス事業,Ｒ サービス業（他に分類されないもの）,Ｓ 公務（他に分類されるものを除く）,Ｔ 分類不能の産業,雇用者（役員を含む）,自営業主（家庭内職者を含む）,家族従業者,KEY_C
8586,272220450,2,羽曳野市,壷井,0,NaN,NaN,254,4,4,-,-,29,61,1,3,15,30,4,3,5,13,6,8,35,-,15,9,13,212,25,10,27222045000

In [62]:
data[data["KEY_CODE"] == 272220450]

,KEY_CODE,HYOSYO,CITYNAME,NAME,HTKSYORI,HTKSAKI,GASSAN,総数,Ａ 農業、林業,うち農業,Ｂ 漁業,Ｃ 鉱業、採石業、砂利採取業,Ｄ 建設業,Ｅ 製造業,Ｆ 電気・ガス・熱供給・水道業,Ｇ 情報通信業,Ｈ 運輸業、郵便業,Ｉ 卸売業、小売業,Ｊ 金融業、保険業,Ｋ 不動産業、物品賃貸業,Ｌ 学術研究、専門・技術サービス業,Ｍ 宿泊業、飲食サービス業,Ｎ 生活関連サービス業、娯楽業,Ｏ 教育、学習支援業,Ｐ 医療、福祉,Ｑ 複合サービス事業,Ｒ サービス業（他に分類されないもの）,Ｓ 公務（他に分類されるものを除く）,Ｔ 分類不能の産業,雇用者（役員を含む）,自営業主（家庭内職者を含む）,家族従業者,KEY_C
8586,272220450,2,羽曳野市,壷井,0,NaN,NaN,254,4,4,-,-,29,61,1,3,15,30,4,3,5,13,6,8,35,-,15,9,13,212,25,10,27222045000

In [65]:
data[data["KEY_C"] == "27222025000"]

,KEY_CODE,HYOSYO,CITYNAME,NAME,HTKSYORI,HTKSAKI,GASSAN,総数,Ａ 農業、林業,うち農業,Ｂ 漁業,Ｃ 鉱業、採石業、砂利採取業,Ｄ 建設業,Ｅ 製造業,Ｆ 電気・ガス・熱供給・水道業,Ｇ 情報通信業,Ｈ 運輸業、郵便業,Ｉ 卸売業、小売業,Ｊ 金融業、保険業,Ｋ 不動産業、物品賃貸業,Ｌ 学術研究、専門・技術サービス業,Ｍ 宿泊業、飲食サービス業,Ｎ 生活関連サービス業、娯楽業,Ｏ 教育、学習支援業,Ｐ 医療、福祉,Ｑ 複合サービス事業,Ｒ サービス業（他に分類されないもの）,Ｓ 公務（他に分類されるものを除く）,Ｔ 分類不能の産業,雇用者（役員を含む）,自営業主（家庭内職者を含む）,家族従業者,KEY_C
8557,272220250,2,羽曳野市,向野,0,NaN,NaN,814,3,3,-,-,45,139,-,7,50,216,5,19,7,46,29,15,99,1,43,8,82,600,120,52,27222025000
8558,27222025000,3,羽曳野市,向野,0,NaN,NaN,147,1,1,-,-,10,33,-,1,13,27,-,2,2,7,7,2,25,-,8,2,7,122,16,4,27222025000

In [67]:
osaka_geo[osaka_geo["KEY_C"] == "27222025000"]

,KEY_CODE,PREF,CITY,S_AREA,PREF_NAME,CITY_NAME,S_NAME,KIGO_E,HCODE,AREA,PERIMETER,H27KAxx_,H27KAxx_ID,KEN,KEN_NAME,SITYO_NAME,GST_NAME,CSS_NAME,KIHON1,DUMMY1,KIHON2,KEYCODE1,KEYCODE2,AREA_MAX_F,KIGO_D,N_KEN,N_CITY,KIGO_I,MOJI,KBSUM,JINKO,SETAI,X_CODE,Y_CODE,KCODE1,geometry,KEY_C
7142,27222025000,27,222,025000,大阪府,羽曳野市,向野,E1,8101,19401.282,1018.917,4284,4283,27,大阪府,None,羽曳野市,None,0250,-,00,222025000,222025000,M,None,None,None,None,向野,6,296,126,135.58030,34.55724,0250-00,"POLYGON ((135.58040 34.55646, 135.58064 34.556...",27222025000
7143,27222025000,27,222,025000,大阪府,羽曳野市,向野,E2,8101,16561.083,614.340,4286,4285,27,大阪府,None,羽曳野市,None,0250,-,00,222025000,222025000,None,None,None,None,None,向野,0,0,0,135.57505,34.56283,0250-00,"POLYGON ((135.57441 34.56209, 135.57467 34.562...",27222025000
7144,27222025000,27,222,025000,大阪府,羽曳野市,向野,E3,8101,15020.858,566.384,4285,4284,27,大阪府,None,羽曳野市,None,0250,-,00,222025000,222025000,None,None,None,None,None,向野,0,0,0,135.57578,34.55994,0250-00,"POLYGON ((135.57671 34.56029, 135.57689 34.559...",27222025000

In [68]:
osaka_geo[osaka_geo["KEY_CODE"] == 272220250]

Empty GeoDataFrame
Columns: [KEY_CODE, PREF, CITY, S_AREA, PREF_NAME, CITY_NAME, S_NAME, KIGO_E, HCODE, AREA, PERIMETER, H27KAxx_, H27KAxx_ID, KEN, KEN_NAME, SITYO_NAME, GST_NAME, CSS_NAME, KIHON1, DUMMY1, KIHON2, KEYCODE1, KEYCODE2, AREA_MAX_F, KIGO_D, N_KEN, N_CITY, KIGO_I, MOJI, KBSUM, JINKO, SETAI, X_CODE, Y_CODE, KCODE1, geometry, KEY_C]
Index: []

In [69]:
osaka_geo[osaka_geo["S_NAME"] == "向野"]

,KEY_CODE,PREF,CITY,S_AREA,PREF_NAME,CITY_NAME,S_NAME,KIGO_E,HCODE,AREA,PERIMETER,H27KAxx_,H27KAxx_ID,KEN,KEN_NAME,SITYO_NAME,GST_NAME,CSS_NAME,KIHON1,DUMMY1,KIHON2,KEYCODE1,KEYCODE2,AREA_MAX_F,KIGO_D,N_KEN,N_CITY,KIGO_I,MOJI,KBSUM,JINKO,SETAI,X_CODE,Y_CODE,KCODE1,geometry,KEY_C
7142,27222025000,27,222,025000,大阪府,羽曳野市,向野,E1,8101,19401.282,1018.917,4284,4283,27,大阪府,None,羽曳野市,None,0250,-,00,222025000,222025000,M,None,None,None,None,向野,6,296,126,135.58030,34.55724,0250-00,"POLYGON ((135.58040 34.55646, 135.58064 34.556...",27222025000
7143,27222025000,27,222,025000,大阪府,羽曳野市,向野,E2,8101,16561.083,614.340,4286,4285,27,大阪府,None,羽曳野市,None,0250,-,00,222025000,222025000,None,None,None,None,None,向野,0,0,0,135.57505,34.56283,0250-00,"POLYGON ((135.57441 34.56209, 135.57467 34.562...",27222025000
7144,27222025000,27,222,025000,大阪府,羽曳野市,向野,E3,8101,15020.858,566.384,4285,4284,27,大阪府,None,羽曳野市,None,0250,-,00,222025000,222025000,None,None,None,None,None,向野,0,0,0,135.57578,34.55994,0250-00,"POLYGON ((135.57671 34.56029, 135.57689 34.559...",27222025000

In [71]:
test_0723 = osaka_geo[osaka_geo["KEY_C"] == "27222025000"]
test_0723.iloc[0, -2]

In [72]:
test_0723.iloc[1, -2]

In [73]:
test_0723.iloc[2, -2]

In [76]:
import folium

In [75]:
!pip install folium

Collecting folium
  Using cached folium-0.11.0-py2.py3-none-any.whl (93 kB)
Collecting branca>=0.3.0
  Using cached branca-0.4.1-py3-none-any.whl (24 kB)
Requirement already satisfied: numpy in /home/hideogawa/ubu-venv/lib/python3.8/site-packages (from folium) (1.19.1)
Requirement already satisfied: requests in /home/hideogawa/ubu-venv/lib/python3.8/site-packages (from folium) (2.24.0)
Requirement already satisfied: jinja2>=2.9 in /home/hideogawa/ubu-venv/lib/python3.8/site-packages (from folium) (2.11.2)
Requirement already satisfied: idna<3,>=2.5 in /home/hideogawa/ubu-venv/lib/python3.8/site-packages (from requests->folium) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /home/hideogawa/ubu-venv/lib/python3.8/site-packages (from requests->folium) (2020.6.20)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/hideogawa/ubu-venv/lib/python3.8/site-packages (from requests->folium) (1.25.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /home/hideogawa/ubu-venv/lib/python3.8/site-packages (from requests->folium) (3.0.4)
Requirement already satisfied: MarkupSafe>=0.23 in /home/hideogawa/ubu-venv/lib/python3.8/site-packages (from jinja2>=2.9->folium) (1.1.1)
Installing collected packages: branca, folium
Successfully installed branca-0.4.1 folium-0.11.0

In [80]:
m = folium.Map([test_0723.iloc[0, -4], test_0723.iloc[0,-5]], zoom_start=15)
folium.GeoJson(test_0723.iloc[0, -2]).add_to(m)
folium.GeoJson(test_0723.iloc[1, -2]).add_to(m)
folium.GeoJson(test_0723.iloc[2, -2]).add_to(m)

m